### ISSUE TITLE
Improve README with full setup

### ISSUE THREAD

**Issue by fev4** [denn1s/vite-plugin-linaria#1]
Hi,

I've been trying to use this but I'm not totally sure what are all the required steps in order to make it work.

I'm trying to make this work with Svelte but with no success. Perhaps the README can be improved in this regard?

**Comment by denn1s** [comment]
Supposedly, it doesn't need any more setup besides installing and adding it to viteConfig, so maybe the issue is it not working with Svelte. Do you have an error message or a sample project at hand?

**Comment by fev4** [comment]
Oh sorry!
Totally my bad. I was actually following [linaria's svelte rollup config](https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md#Rollup-1) plus your vite-plugin-linaria and it was showing some weird errors.

But by simply ignoring linaria's config and only adding `@sveltejs/vite-plugin-svelte` everything works impressively smooth.

```javascript
import { defineConfig } from 'vite';
import svelte from '@sveltejs/vite-plugin-svelte';
import VitePluginLinaria from 'vite-plugin-linaria';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svelte(), VitePluginLinaria()],
});
```

I'm... without words haha, lost a bit of time trying to follow linaria's config. Awesome work you've done!

Now I'm wondering how to use `styled` from Linaria within Svelte, but that's a question for another time.

Closing issue. Thanks again!
